export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const GET_CURRENT_ACCOUNT = 'GET_CURRENT_ACCOUNT';

// hotel
export const FETCH_HOTEL= 'FETCH_HOTEL';
export const FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE';
export const GET_HOTEL = 'GET_HOTEL';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const GET_REVIEW_DETAIL = 'GET_REVIEW_DETAIL';
export const GET_MY_REVIEWS = 'GET_MY_REVIEWS';
export const GET_PENDING_REVIEWS = 'GET_PENDING_REVIEWS';
export const LIKE_REVIEW = 'LIKE_REVIEW';
export const DISLIKE_REVIEW = 'DISLIKE_REVIEW';
export const UNDISLIKE_REVIEW = 'UNDISLIKE_REVIEW';
export const UNLIKE_REVIEW = 'UNLIKE_REVIEW';
export const SUBMIT_REVIEW = 'SUBMIT_REVIEW';
export const GET_MY_VOTED = 'GET_MY_VOTED';